include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - example/**.dart

linter:
  rules:
    - constant_identifier_names
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals